### ISSUE TITLE
Cannot read property 'username' of undefined

### ISSUE THREAD

**Issue by rhalff** [exoframejs/exoframe#1]
I receive an error when executing the command `exoframe build`

Probably it's unexpected first usage, but below is the error I receive.

```coffee
 $ exoframe --help

Installing missing plugin: exoframe-template-node
Installing missing plugin: exoframe-template-maven
Installing missing plugin: exoframe-template-nginx
Commands:
  endpoint <url>  set exoframe server URL
  login           login into exoframe server
  build           build current folder using exoframe server
  list [type]     list your images on exoframe server
  deploy [image]  deploy image on exoframe server
  status          get exoframe status info
  stop [service]  stop running service on exoframe server
  rm [service]    remove non-running service on exoframe server
  pull <image>    pull image from registry on exoframe server
  update          update exoframe plugins immediately

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]

$ cd /srv/psichi/git/chix-server

$ exoframe build

Building current folder using endpoint: http://localhost:3000
Using template: Dockerfile Exoframe Template
? Image tag: chix-server
? Custom label: 
Trace: Unhandled rejection: TypeError: Cannot read property 'username' of undefined
    at Object.<anonymous> (/home/rhalff/.nvm/versions/node/v6.4.0/lib/node_modules/exoframe/dist/build.js:141:45)
    at next (native)
    at step (/home/rhalff/.nvm/versions/node/v6.4.0/lib/node_modules/exoframe/dist/build.js:56:191)
    at /home/rhalff/.nvm/versions/node/v6.4.0/lib/node_modules/exoframe/dist/build.js:56:368
    at process.on.error (/home/rhalff/.nvm/versions/node/v6.4.0/lib/node_modules/exoframe/dist/index.js:77:51)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at emitPendingUnhandledRejections (internal/process/promises.js:44:22)
    at runMicrotasksCallback (internal/process/next_tick.js:61:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

The contents of the config at that stage is:
```json
{
    "endpoint": "http://localhost:3000",
    "plugins": {
      "templates": [
        "exoframe-template-node",
        "exoframe-template-maven",
        "exoframe-template-nginx"
      ]
 }
```

**Comment by yamalight** [comment]
Hey! Thanks for the report. 
It looks like you forgot to execute `exoframe login` so it cannot get your username from request.
Can you try doing `exoframe login` and then running build again and let me know if that works?

**Comment by yamalight** [comment]
@rhalff just published a new version, it now should correctly warn you about this issue. Please let me know if it still happens anywhere :)

**Comment by rhalff** [comment]
Thanks, I've upgraded and it works correctly now.

**Comment by yamalight** [comment]
@rhalff great! thanks for reporting.
