### ISSUE TITLE
Bizarre Relative Paths

### ISSUE THREAD

**Issue by robgraeber** [exoframejs/exoframe#132]
So I'm trying to deploy this app: https://github.com/effinggames/personal-site

Which is a pretty basic express.js app with a gulp build step. It seems like it's converting ./Main.js
to ./src/Main.js for some reason which is breaking the build. 

```
2018-4-8 12:01:58 > personal-site@1.0.0 start /usr/src/app
2018-4-8 12:01:58 > npm run build && node ./src/Main.js
2018-4-8 12:01:58 
2018-4-8 12:01:58 
2018-4-8 12:01:58 > personal-site@1.0.0 build /usr/src/app
2018-4-8 12:01:58 > gulp build
2018-4-8 12:01:58 
2018-4-8 12:01:59 [12:01:59] Using gulpfile /usr/src/app/Gulpfile.js
2018-4-8 12:01:59 [12:01:59] Starting 'clean'...
2018-4-8 12:01:59 Cleaning: /usr/src/app/public
2018-4-8 12:01:59 [12:01:59] Finished 'clean' after 22 ms
2018-4-8 12:01:59 [12:01:59] Starting 'build'...
2018-4-8 12:02:08 [12:02:08] Version: webpack 1.15.0
2018-4-8 12:02:08                   Asset     Size  Chunks             Chunk Names
2018-4-8 12:02:08 3c473d28978fc071c977.js  4.15 MB       0  [emitted]  main
2018-4-8 12:02:08 [12:02:08] Finished 'build' after 8.85 s
2018-4-8 12:02:09 [12:02:09] gulp-imagemin: Minified 3 images (saved 31.63 kB - 17.3%)
   internal/modules/cjs/loader.js:550
       throw err;
       ^
   
   Error: Cannot find module '/usr/src/app/src/Main.js'
       at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
       at Function.Module._load (internal/modules/cjs/loader.js:475:25)
       at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
       at startup (internal/bootstrap/node.js:201:19)
       at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
   npm ERR! code ELIFECYCLE
   npm ERR! errno 1
   npm ERR! personal-site@1.0.0 start: `npm run build && node ./src/Main.js`
   npm ERR! Exit status 1
   npm ERR! 
   npm ERR! Failed at the personal-site@1.0.0 start script.
   npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
   
   npm ERR! A complete log of this run can be found in:
   npm ERR!     /root/.npm/_logs/2018-04-08T12_02_09_428Z-debug.log
```

**Comment by robgraeber** [comment]
@yamalight sorry that was it, I should probably get some sleep

**Comment by yamalight** [comment]
no worries 😂
