### ISSUE TITLE
docker-compose fails to deploy

### ISSUE THREAD

**Issue by dmitrym0** [exoframejs/exoframe#146]
Hello,

I'm attempting to deploy a docker-compose project, with not much luck. As far as I can tell server startup and login went through ok, but the actual deployment fails:

```
/t/test-local ❯❯❯ exoframe --verbose
Deploying current project to endpoint: http://localhost:8080

No .exoframeignore file found, using default ignores

Ignoring following paths: [ '.git', 'node_modules', '.exoframeignore' ]
[info] Deploying docker-compose project..
Error deploying project: Error: Something went wrong!
Build log:

No log available

Original error: { Error: Something went wrong!
    at Object.exports.handler (/usr/local/lib/node_modules/exoframe/src/commands/deploy.js:191:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) response: {} }
```

**Comment by yamalight** [comment]
Hi @dmitrym0. Can you please try to execute it with `exoframe -vvv` and post the log here?

**Comment by dmitrym0** [comment]
Here you go @yamalight 

```
/t/test-local ❯❯❯ docker ps
CONTAINER ID        IMAGE                 COMMAND              CREATED             STATUS              PORTS                    NAMES
4ab0c0f546e6        exoframe/server       "/exoframe-server"   4 hours ago         Up 4 hours          0.0.0.0:8080->8080/tcp   exoframe-server
d23ef8d81121        portainer/portainer   "/portainer"         4 days ago          Up 4 days           0.0.0.0:9000->9000/tcp   compassionate_spence
/t/test-local ❯❯❯ exoframe endpoint
? Choose endpoint: http://localhost:8080
/t/test-local ❯❯❯ exoframe -vvv
Deploying current project to endpoint: http://localhost:8080

No .exoframeignore file found, using default ignores

Ignoring following paths: [ '.git', 'node_modules', '.exoframeignore' ]
[info] Deploying docker-compose project..
Error deploying project: Error: Something went wrong!
Build log:

No log available

Original error: { Error: Something went wrong!
    at Object.exports.handler (/usr/local/lib/node_modules/exoframe/src/commands/deploy.js:191:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) response: {} }
Original response: {}
```

**Comment by yamalight** [comment]
@dmitrym0 that is very strange. could you please share your docker-compose file so I can test this?

**Comment by yamalight** [comment]
Closing this due to inactivity. Feel free to re-open if needed.
