### ISSUE TITLE
Add parameters validation while configuring exoframe.json

### ISSUE THREAD

**Issue by samohovets** [exoframejs/exoframe#155]
For example, if i put something like "hello" into labels or env vars question while running `exoframe config`all the stuff will go wrong:
```
TypeError: Cannot read property 'trim' of undefined
    at config.labels.labels.split.map.map.pair (/Users/igor/Projects/exoframe/client/src/commands/config.js:131:58)
    at Array.map (<anonymous>)
    at Object.exports.handler (/Users/igor/Projects/exoframe/client/src/commands/config.js:131:8)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by yamalight** [comment]
Totally forgot to add this. Thanks! 👍

**Comment by samohovets** [comment]
I'll try to contribute to this first time 😄
