### ISSUE TITLE
exoframe endpoint failed

### ISSUE THREAD

**Issue by smirnp** [exoframejs/exoframe#157]
Hi! 
I'm stuck at the following command (the server is started with 127.0.0.1):
```
exoframe endpoint http://127.0.0.1
/usr/lib/node_modules/exoframe/src/commands/login.js:34
exports.handler = async ({key, passphrase, url}) => {
                        ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/exoframe/src/index.js:14:15)
```

The server looks like successfully started (2 containers) by the following command:
```
docker run -d \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /path/to/exoframe-folder:/root/.exoframe \
-v /home/user/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro \
-e EXO_PRIVATE_KEY=your_private_key \
--label traefik.backend=exoframe-server \
--label traefik.frontend.rule=Host:127.0.0.1 \
--restart always \
--name exoframe-server \
exoframe/server

```

**Comment by yamalight** [comment]
@smirnp it looks like you are using old node.js version, you need at least node 8 (and since it's current LTS I'd recommend using it anyway)

**Comment by smirnp** [comment]
That helped! Thanks!
