### ISSUE TITLE
Build log contains error

### ISSUE THREAD

**Issue by abnerlee** [exoframejs/exoframe#164]
I'm trying to deploy https://github.com/go-gitea/gitea

After clone it, I added `exoframe.json` config

```
{
  "name": "gitea",
  "restart": "on-failure:2",
  "template": "dockerfile"
}
```

But I met the error after I run `exoframe`, logs before final error are:

```
[verbose]  ---> Running in e668ca71fb0c

[verbose] Removing intermediate container e668ca71fb0c

[verbose]  ---> 6986099127e3

[verbose] Step 19/21 : COPY docker /
[verbose]

[verbose]  ---> a89f1a40947c

[verbose] Step 20/21 : COPY --from=build-env /go/src/code.gitea.io/gitea/gitea /app/gitea/gitea
[verbose]

[verbose]  ---> 23d888bb9d1a

[verbose] Step 21/21 : RUN ln -s /app/gitea/gitea /usr/local/bin/gitea
[verbose]

[verbose]  ---> Running in 7227c1198503

[verbose] Removing intermediate container 7227c1198503

[verbose]  ---> 5ee7ac0407b5

[verbose] {"aux":{"ID":"sha256:5ee7ac0407b5df20b9515a7ae2e83e33dac378d175b06fe97de10865f40c47b7"}}
[verbose] Successfully built 5ee7ac0407b5

[verbose] Successfully tagged exo-root-gitea:latest

[error] Build log contains errors!
{
  "message": "Build log contains errors!",
  "level": "error"
}
Error deploying project: Error: Build log contains errors!
Build log:

No log available

Original error: { Error: Build log contains errors!
    at Stream.stream.on.str (C:\Users\ab\AppData\Roaming\nvm\v8.1.0\node_modules\exoframe\src\commands\deploy.js:48:19)
    at emitOne (events.js:115:13)
    at Stream.emit (events.js:210:7)
    at Stream._send (C:\Users\{my-user-name}\AppData\Roaming\nvm\v8.1.0\node_modules\exoframe\node_modules\highland\lib\index.js:994:18)
    at push (C:\Users\{my-user-name}\AppData\Roaming\nvm\v8.1.0\node_modules\exoframe\node_modules\highland\lib\index.js:1515:19)
    at C:\Users\{my-user-name}\AppData\Roaming\nvm\v8.1.0\node_modules\exoframe\node_modules\highland\lib\index.js:2477:17
    at Stream.s._send (C:\Users\{my-user-name}\AppData\Roaming\nvm\v8.1.0\node_modules\exoframe\node_modules\highland\lib\index.js:1549:9)
    at Stream.write (C:\Users\{my-user-name}\AppData\Roaming\nvm\v8.1.0\node_modules\exoframe\node_modules\highland\lib\index.js:1650:18)
    at Stream._send (C:\Users\{my-user-name}\AppData\Roaming\nvm\v8.1.0\node_modules\exoframe\node_modules\highland\lib\index.js:974:26)
    at push (C:\Users\{my-user-name}\AppData\Roaming\nvm\v8.1.0\node_modules\exoframe\node_modules\highland\lib\index.js:1515:19)
  response: { message: 'Build log contains errors!', level: 'error' } }
Original response: { message: 'Build log contains errors!', level: 'error' }
```

No related error/warnings except the last exceptions in log. Any suggestions on this?

**Comment by yamalight** [comment]
@abnerlee the error handling was changed in 3.1 - could you try using [nightly versions](https://github.com/exoframejs/exoframe/blob/master/docs/Nightly.md) of server and cli and let me know if that works?

**Comment by abnerlee** [comment]
After update, I got:

```
[verbose] Step 18/21 : CMD ["/bin/s6-svscan", "/etc/s6"]
[verbose]

[verbose]  ---> Using cache

[verbose]  ---> 6986099127e3

[verbose] Step 19/21 : COPY docker /
[verbose]

[verbose]  ---> Using cache

[verbose]  ---> a89f1a40947c

[verbose] Step 20/21 : COPY --from=build-env /go/src/code.gitea.io/gitea/gitea /app/gitea/gitea
[verbose]

[verbose]  ---> Using cache

[verbose]  ---> 23d888bb9d1a

[verbose] Step 21/21 : RUN ln -s /app/gitea/gitea /usr/local/bin/gitea
[verbose]

[verbose]  ---> Using cache

[verbose]  ---> 5ee7ac0407b5

[verbose] {"aux":{"ID":"sha256:5ee7ac0407b5df20b9515a7ae2e83e33dac378d175b06fe97de10865f40c47b7"}}
[verbose] Successfully built 5ee7ac0407b5

[verbose] Successfully tagged exo-root-gitea:latest

[verbose] Starting container with following config:
[error] undefined
{
  "level": "error"
}
Error deploying project: Error
Build log:

No log available

Original error: { Error
    at Stream.stream.on.str (C:\Users\ab\AppData\Roaming\nvm\v8.1.0\node_modules\exoframe\src\commands\deploy.js:48:19)
    at emitOne (events.js:115:13)
    at Stream.emit (events.js:210:7)
    at Stream._send (C:\Users\{my-user-name}\AppData\Roaming\nvm\v8.1.0\node_modules\exoframe\node_modules\highland\lib\index.js:994:18)
    at push (C:\Users\{my-user-name}\AppData\Roaming\nvm\v8.1.0\node_modules\exoframe\node_modules\highland\lib\index.js:1515:19)
    at C:\Users\{my-user-name}\AppData\Roaming\nvm\v8.1.0\node_modules\exoframe\node_modules\highland\lib\index.js:2477:17
    at Stream.s._send (C:\Users\{my-user-name}\AppData\Roaming\nvm\v8.1.0\node_modules\exoframe\node_modules\highland\lib\index.js:1549:9)
    at Stream.write (C:\Users\{my-user-name}\AppData\Roaming\nvm\v8.1.0\node_modules\exoframe\node_modules\highland\lib\index.js:1650:18)
    at Stream._send (C:\Users\{my-user-name}\AppData\Roaming\nvm\v8.1.0\node_modules\exoframe\node_modules\highland\lib\index.js:974:26)
    at push (C:\Users\{my-user-name}\AppData\Roaming\nvm\v8.1.0\node_modules\exoframe\node_modules\highland\lib\index.js:1515:19) response: { level: 'error' } }
Original response: { level: 'error' }
```

**Comment by yamalight** [comment]
can you try running exoframe-server in [debug mode](https://github.com/exoframejs/exoframe-server#configuration) and check exoframe-server logs after deployment fails?

**Comment by abnerlee** [comment]
I tried on a different cluster and seems OK. This seems to be a network issue

**Comment by yamalight** [comment]
OK, great!
