### ISSUE TITLE
Error: Something went wrong!

### ISSUE THREAD

**Issue by maxime1992** [exoframejs/exoframe#199]
Hi,

I'm trying to deploy my app to prod but it's crashing in... 8 out of 10 cases on the frontend task :thinking: 

I've built and Angular (7) app and the error seems to appear when the app is being built.
It's completely fine locally and working sometimes while deploying with Exoframe too.

I ran the deploy like the following:
`exoframe deploy -u -vvv`

And the only message I've got is

```
Error deploying project: Error: Something went wrong!
Build log:

No log available

Original error: { Error: Something went wrong!
    at Object.exports.handler (/home/maxime/.config/yarn/global/node_modules/exoframe/src/commands/deploy.js:218:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) response: {} }
Original response: {}
```

So I'm really not sure what is going on here.

**Comment by yamalight** [comment]
@maxime1992 is your app code public? if not - could you create a simple project that reproduces the issue?

**Comment by yamalight** [comment]
@maxime1992 you should now be able to deploy your project using your image tar file.
to do so - add the following to exoframe project config: 
```json
{
  "image": "imageName",
  "imageFile": "myImage.tar"
}
```
Place that file next to `myImage.tar` (can be generated by running `docker save myImage > myImage.tar` and execute `exoframe deploy` 🤔

**Comment by maxime1992** [comment]
Nice one! That's also a workaround for the private registry issue :smile:!

Is it possible to use that if I'm deploying through a docker-compose file? :thinking:

**Comment by yamalight** [comment]
@maxime1992 nope, that's a separate template and only works as a standalone thing.
doing that with compose would be _very_ tricky

**Comment by yamalight** [comment]
I'm closing this due to inactivity. Feel free to re-open if needed.
