### ISSUE TITLE
Server should correctly return error when template is not found byt name

### ISSUE THREAD

**Issue by yamalight** [exoframejs/exoframe#254]
It should've been patched when we closed https://github.com/exoframejs/exoframe/issues/220 but for some reason following error still occurs when passing name of non-existent template:
```
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'executeTemplate' of undefined
       at deploy (/snapshot/exoframe-server/bin/server-core.js:85322:18)
       at Object.handler (/snapshot/exoframe-server/bin/server-core.js:85409:7)
       at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by yamalight** [comment]
Not sure why this happen but it was indeed covered by #220 🤔 
Closing this as I can't repro
