### ISSUE TITLE
Build warnings make the cli think the build failed

### ISSUE THREAD

**Issue by Tiim** [exoframejs/exoframe#300]
I noticed for a few days now that the exoframe cli almost always shows that the deployment failed, even though in reality the new deployment is running just fine. It seems to be triggered by build warnings.

<details>
<summary>
Here is part of the log when ran with <code>exoframe -v</code>
</summary>

```

[info]
Successfully built 99712f5da7cd
[info] Successfully tagged exo-tim-aqualetics-coach_cron:latest
[info] Docker-compose exited with code 0
[info] Recreating exo-tim-aqualetics-coach-migration-d8ed7760 ...

[info] Recreating exo-tim-aqualetics-coach-migration-d8ed7760 ... done

[info] Recreating exo-tim-aqualetics-coach-client-d8ed7760    ... done
Recreating exo-tim-aqualetics-coach-server-d8ed7760    ... done
[info]
Recreating exo-tim-aqualetics-coach-cron-d8ed7760      ... done
[info]
[info] Docker-compose exited with code 0
[info] Deployment success!
Error deploying project: Error: Module Warning (from ./node_modules/eslint-loader/index.js):

/code/src/components/HeaderLink.vue
   9:62  warning  Insert `·`  prettier/prettier
  13:62  warning  Insert `·`  prettier/prettier

✖ 2 problems (0 errors, 2 warnings)
  0 errors and 2 warnings potentially fixable with the `--fix` option.


Module Warning (from ./node_modules/eslint-loader/index.js):

/code/src/components/Notifications.vue
  29:49   warning  Insert `·`                                              prettier/prettier
  55:134  warning  Replace `⏎··········n.header⏎········` with `n.header`  prettier/prettier

✖ 2 problems (0 errors, 2 warnings)
  0 errors and 2 warnings potentially fixable with the `--fix` option.


Module Warning (from ./node_modules/eslint-loader/index.js):

/code/src/views/admin/GroupCoachAssignement.vue
  67:27  warning  Delete `·`  prettier/prettier

✖ 1 problem (0 errors, 1 warning)
  0 errors and 1 warning potentially fixable with the `--fix` option.


Module Warning (from ./node_modules/eslint-loader/index.js):

/code/src/views/dev/BuildInfo.vue
  24:65  warning  Replace `⏎········this.info.hash⏎······` with `this.info.hash`  prettier/prettier

✖ 1 problem (0 errors, 1 warning)
  0 errors and 1 warning potentially fixable with the `--fix` option.


Module Warning (from ./node_modules/eslint-loader/index.js):

/code/src/views/group/components/GroupAdminSettings.vue
  6:31  warning  Insert `;`  prettier/prettier

✖ 1 problem (0 errors, 1 warning)
  0 errors and 1 warning potentially fixable with the `--fix` option.


Module Warning (from ./node_modules/eslint-loader/index.js):

/code/src/views/list/components/Filters.vue
  116:30  warning  Insert `·`  prettier/prettier

✖ 1 problem (0 errors, 1 warning)
  0 errors and 1 warning potentially fixable with the `--fix` option.


Module Warning (from ./node_modules/eslint-loader/index.js):

/code/src/views/timetable/TimeTable.vue
  135:38  warning  Replace `d.coaches.map((c)·=>·c.user.id),·coaches` with `⏎············d.coaches.map((c)·=>·c.user.id),⏎············coaches⏎··········`  prettier/prettier

✖ 1 problem (0 errors, 1 warning)
  0 errors and 1 warning potentially fixable with the `--fix` option.


You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
 warning

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  js/chunk-vendors.18036a9a.js (434 KiB)

 warning

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (724 KiB)
      css/chunk-vendors.26bdf62f.css
      js/chunk-vendors.18036a9a.js
      css/app.0797fe4d.css
      js/app.21b998b7.js


Build log:

No log available

Original error: Error: Module Warning (from ./node_modules/eslint-loader/index.js):

/code/src/components/HeaderLink.vue
   9:62  warning  Insert `·`  prettier/prettier
  13:62  warning  Insert `·`  prettier/prettier

✖ 2 problems (0 errors, 2 warnings)
  0 errors and 2 warnings potentially fixable with the `--fix` option.


Module Warning (from ./node_modules/eslint-loader/index.js):

/code/src/components/Notifications.vue
  29:49   warning  Insert `·`                                              prettier/prettier
  55:134  warning  Replace `⏎··········n.header⏎········` with `n.header`  prettier/prettier

✖ 2 problems (0 errors, 2 warnings)
  0 errors and 2 warnings potentially fixable with the `--fix` option.


Module Warning (from ./node_modules/eslint-loader/index.js):

/code/src/views/admin/GroupCoachAssignement.vue
  67:27  warning  Delete `·`  prettier/prettier

✖ 1 problem (0 errors, 1 warning)
  0 errors and 1 warning potentially fixable with the `--fix` option.


Module Warning (from ./node_modules/eslint-loader/index.js):

/code/src/views/dev/BuildInfo.vue
  24:65  warning  Replace `⏎········this.info.hash⏎······` with `this.info.hash`  prettier/prettier

✖ 1 problem (0 errors, 1 warning)
  0 errors and 1 warning potentially fixable with the `--fix` option.


Module Warning (from ./node_modules/eslint-loader/index.js):

/code/src/views/group/components/GroupAdminSettings.vue
  6:31  warning  Insert `;`  prettier/prettier

✖ 1 problem (0 errors, 1 warning)
  0 errors and 1 warning potentially fixable with the `--fix` option.


Module Warning (from ./node_modules/eslint-loader/index.js):

/code/src/views/list/components/Filters.vue
  116:30  warning  Insert `·`  prettier/prettier

✖ 1 problem (0 errors, 1 warning)
  0 errors and 1 warning potentially fixable with the `--fix` option.


Module Warning (from ./node_modules/eslint-loader/index.js):

/code/src/views/timetable/TimeTable.vue
  135:38  warning  Replace `d.coaches.map((c)·=>·c.user.id),·coaches` with `⏎············d.coaches.map((c)·=>·c.user.id),⏎············coaches⏎··········`  prettier/prettier

✖ 1 problem (0 errors, 1 warning)
  0 errors and 1 warning potentially fixable with the `--fix` option.


You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
 warning

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  js/chunk-vendors.18036a9a.js (434 KiB)

 warning

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (724 KiB)
      css/chunk-vendors.26bdf62f.css
      js/chunk-vendors.18036a9a.js
      css/app.0797fe4d.css
      js/app.21b998b7.js


    at Stream.<anonymous> (/home/tim/.nvm/versions/node/v12.17.0/lib/node_modules/exoframe/dist/index.js:68404:19)
    at Stream.emit (events.js:315:20)
    at Stream.module.exports.Stream._send (/home/tim/.nvm/versions/node/v12.17.0/lib/node_modules/exoframe/dist/index.js:80196:18)
    at push (/home/tim/.nvm/versions/node/v12.17.0/lib/node_modules/exoframe/dist/index.js:80718:19)
    at /home/tim/.nvm/versions/node/v12.17.0/lib/node_modules/exoframe/dist/index.js:81749:17
    at Stream.s._send (/home/tim/.nvm/versions/node/v12.17.0/lib/node_modules/exoframe/dist/index.js:80752:9)
    at Stream.module.exports.Stream.write (/home/tim/.nvm/versions/node/v12.17.0/lib/node_modules/exoframe/dist/index.js:80853:18)
    at Stream.module.exports.Stream._send (/home/tim/.nvm/versions/node/v12.17.0/lib/node_modules/exoframe/dist/index.js:80176:26)
    at push (/home/tim/.nvm/versions/node/v12.17.0/lib/node_modules/exoframe/dist/index.js:80718:19)
    at /home/tim/.nvm/versions/node/v12.17.0/lib/node_modules/exoframe/dist/index.js:82363:13 {
  response: {
    message: 'Module Warning (from ./node_modules/eslint-loader/index.js):\n' +
      '\n' +
      '/code/src/components/HeaderLink.vue\n' +
      '   9:62  warning  Insert `·`  prettier/prettier\n' +
      '  13:62  warning  Insert `·`  prettier/prettier\n' +
      '\n' +
      '✖ 2 problems (0 errors, 2 warnings)\n' +
      '  0 errors and 2 warnings potentially fixable with the `--fix` option.\n' +
      '\n' +
      '\n' +
      'Module Warning (from ./node_modules/eslint-loader/index.js):\n' +
      '\n' +
      '/code/src/components/Notifications.vue\n' +
      '  29:49   warning  Insert `·`                                              prettier/prettier\n' +
      '  55:134  warning  Replace `⏎··········n.header⏎········` with `n.header`  prettier/prettier\n' +
      '\n' +
      '✖ 2 problems (0 errors, 2 warnings)\n' +
      '  0 errors and 2 warnings potentially fixable with the `--fix` option.\n' +
      '\n' +
      '\n' +
      'Module Warning (from ./node_modules/eslint-loader/index.js):\n' +
      '\n' +
      '/code/src/views/admin/GroupCoachAssignement.vue\n' +
      '  67:27  warning  Delete `·`  prettier/prettier\n' +
      '\n' +
      '✖ 1 problem (0 errors, 1 warning)\n' +
      '  0 errors and 1 warning potentially fixable with the `--fix` option.\n' +
      '\n' +
      '\n' +
      'Module Warning (from ./node_modules/eslint-loader/index.js):\n' +
      '\n' +
      '/code/src/views/dev/BuildInfo.vue\n' +
      '  24:65  warning  Replace `⏎········this.info.hash⏎······` with `this.info.hash`  prettier/prettier\n' +
      '\n' +
      '✖ 1 problem (0 errors, 1 warning)\n' +
      '  0 errors and 1 warning potentially fixable with the `--fix` option.\n' +
      '\n' +
      '\n' +
      'Module Warning (from ./node_modules/eslint-loader/index.js):\n' +
      '\n' +
      '/code/src/views/group/components/GroupAdminSettings.vue\n' +
      '  6:31  warning  Insert `;`  prettier/prettier\n' +
      '\n' +
      '✖ 1 problem (0 errors, 1 warning)\n' +
      '  0 errors and 1 warning potentially fixable with the `--fix` option.\n' +
      '\n' +
      '\n' +
      'Module Warning (from ./node_modules/eslint-loader/index.js):\n' +
      '\n' +
      '/code/src/views/list/components/Filters.vue\n' +
      '  116:30  warning  Insert `·`  prettier/prettier\n' +
      '\n' +
      '✖ 1 problem (0 errors, 1 warning)\n' +
      '  0 errors and 1 warning potentially fixable with the `--fix` option.\n' +
      '\n' +
      '\n' +
      'Module Warning (from ./node_modules/eslint-loader/index.js):\n' +
      '\n' +
      '/code/src/views/timetable/TimeTable.vue\n' +
      '  135:38  warning  Replace `d.coaches.map((c)·=>·c.user.id),·coaches` with `⏎············d.coaches.map((c)·=>·c.user.id),⏎············coaches⏎··········`  prettier/prettier\n' +
      '\n' +
      '✖ 1 problem (0 errors, 1 warning)\n' +
      '  0 errors and 1 warning potentially fixable with the `--fix` option.\n' +
      '\n' +
      '\n' +
      'You may use special comments to disable some warnings.\n' +
      'Use // eslint-disable-next-line to ignore the next line.\n' +
      'Use /* eslint-disable */ to ignore all warnings in a file.\n' +
      ' warning  \n' +
      '\n' +
      'asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).\n' +
      'This can impact web performance.\n' +
      'Assets: \n' +
      '  js/chunk-vendors.18036a9a.js (434 KiB)\n' +
      '\n' +
      ' warning  \n' +
      '\n' +
      'entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.\n' +
      'Entrypoints:\n' +
      '  app (724 KiB)\n' +
      '      css/chunk-vendors.26bdf62f.css\n' +
      '      js/chunk-vendors.18036a9a.js\n' +
      '      css/app.0797fe4d.css\n' +
      '      js/app.21b998b7.js\n' +
      '\n',
    level: 'error'
  }
}
```

</details>

According to the log the docker-compose exited with status code 0 and still exoframe thinks that it somehow failed?

**Comment by yamalight** [comment]
Docker is a bit iffy with reporting failed builds (i.e. I found that it can report build as successful even though there were errors and it didn't finish), so Exoframe looks for anything coming from `stderr` side during `docker build` (see [this](https://github.com/exoframejs/exoframe-server/blob/master/src/docker/build.js#L33)) and considers build failed if there's stuff in there.

I'm guessing your eslint writes into `stderr`, hence Exoframe considers that to be failed build.

**Comment by Tiim** [comment]
Oh that might be the case. I recently upgraded eslint so maybe it didn't do that before. Thanks :)
