### ISSUE TITLE
Debugging deploys

### ISSUE THREAD

**Issue by benmerckx** [exoframejs/exoframe#89]
After about 2 minutes I run into some internal server error while deploying. I tried this on a static project, as well as a docker-compose project. I've set debug to true in `~/.exoframe/server.config.yml`, but so far I keep getting the same result:
````
Deploying current project to endpoint: https://...
✖ Deployment failed!
Error deploying project: Internal Server Error
Build log:

No log available
````
Is there an easy way to debug this situation?

**Comment by yamalight** [comment]
Hi @benmerckx! What kind of specs does the server has? Exoframe typically needs ~512MB of RAM and ~ 500MB of HDD space to work without issues.
If your server has that - can you please run deploy in verbose mode `exoframe -vvv` and share the output?

**Comment by benmerckx** [comment]
Looks like there should be enough memory to build the containers:
````
              total        used        free      shared  buff/cache   available
Mem:           3.8G        446M        1.6G         66M        1.8G        3.1G
Swap:          1.9G          0B        1.9G
````
(Unrelated suggestion: building the containers on the client side and transferring a docker export might be cool)

Deploying with `exoframe -vvv` gives me (for docker-compose):

````
Deploying current project to endpoint: https://...

Ignoring following paths: [ '.git', 'node_modules' ]
[info] Deploying docker-compose project..
[verbose] Compose file modified
[info] 'network_mode' and 'networks' cannot be combined
[info] Docker-compose exited with code 1
[error] Error parsing line: Internal Server Error
Error deploying project: Internal Server Error
Build log:

No log available

Original error: { Error: Error parsing output!
    at Stream.stream.on.str (/usr/lib/node_modules/exoframe/src/commands/deploy.js:52:17)
    at emitOne (events.js:116:13)
    at Stream.emit (events.js:211:7)
    at Stream._send (/usr/lib/node_modules/exoframe/node_modules/highland/lib/index.js:979:18)
    at push (/usr/lib/node_modules/exoframe/node_modules/highland/lib/index.js:1498:19)
    at /usr/lib/node_modules/exoframe/node_modules/highland/lib/index.js:2435:17
    at Stream.s._send (/usr/lib/node_modules/exoframe/node_modules/highland/lib/index.js:1532:9)
    at Stream.write (/usr/lib/node_modules/exoframe/node_modules/highland/lib/index.js:1633:18)
    at Stream._send (/usr/lib/node_modules/exoframe/node_modules/highland/lib/index.js:959:26)
    at push (/usr/lib/node_modules/exoframe/node_modules/highland/lib/index.js:1498:19) response: { error: 'Internal Server Error' } }
Original response: { error: 'Internal Server Error' }
````

So apparently in my eager to try this I had `network_mode: host` left in my docker-compose configuration file from a copy-paste. Locally this works, but as exoframe seems to add a few properties (network ea.) to docker-compose files this is what happens :) Removing `network_mode` things now seem to work fine.

On to the static projects failing... The verbose option gave me:
```
Deploying current project to endpoint: https://...

Ignoring following paths: [ '.git', 'node_modules' ]
[info] Deploying Static HTML project..
[verbose] Using dockerfile..
[verbose] Building image with tag: exo-username-:latest
[error] Error parsing line: Internal Server Error
Error deploying project: Internal Server Error
Build log:

No log available

Original error: { Error: Error parsing output!
    at Stream.stream.on.str (/usr/lib/node_modules/exoframe/src/commands/deploy.js:52:17)
    at emitOne (events.js:116:13)
    at Stream.emit (events.js:211:7)
    at Stream._send (/usr/lib/node_modules/exoframe/node_modules/highland/lib/index.js:979:18)
    at push (/usr/lib/node_modules/exoframe/node_modules/highland/lib/index.js:1498:19)
    at /usr/lib/node_modules/exoframe/node_modules/highland/lib/index.js:2435:17
    at Stream.s._send (/usr/lib/node_modules/exoframe/node_modules/highland/lib/index.js:1532:9)
    at Stream.write (/usr/lib/node_modules/exoframe/node_modules/highland/lib/index.js:1633:18)
    at Stream._send (/usr/lib/node_modules/exoframe/node_modules/highland/lib/index.js:959:26)
    at push (/usr/lib/node_modules/exoframe/node_modules/highland/lib/index.js:1498:19) response: { error: 'Internal Server Error' } }
Original response: { error: 'Internal Server Error' }
```
I noticed the tag looked weird, ending in a dash. My `exoframe.json` looked like this: 
````
{
  "restart": "on-failure:2",
  "domain": "..."
}
````
I tried adding the name property, which fixes the tag and proceeds to deploy fine. The docs currently state the name should default to the folder name, but it seems not to be the case.

**Comment by yamalight** [comment]
@benmerckx aha, looks like your `exoframe.json` is missing `"name"` property and constructed image name (`exo-username-:latest`) is broken because of that. 
For now you can either edit json manually or use `exoframe config` command to fix that, but that's definitely something that should be validated in CLI before deploy 🤔

**Comment by yamalight** [comment]
I'm going to close it since there's no more questions. Feel free to re-open if you have more issues.

**Comment by abnerlee** [comment]
@yamalight Hi, I'm unable to see upload progress.

After I run `exoframe --v`

The will print 
```
Deploying current project to endpoint: http://exoframe.{my-domain}

Ignoring following paths: [ '.git', 'node_modules', '.exoframeignore' ]
```
but nothing more, I'm unable to know if it is running or get frozen

**Comment by yamalight** [comment]
@abnerlee there's currently no upload progress display, only build and deploy. probably something that should be added though 🤔
