### ISSUE TITLE
Error after installing exoframe server

### ISSUE THREAD

**Issue by M0ter** [exoframejs/exoframe#99]
Hello, i get this error in the docker logs.

```
TypeError: server.connection is not a function
    at Object.<anonymous> (/snapshot/exoframe-server/src/index.js:18:8)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:644:10)
    at Module.load (module.js:552:32)
    at tryModuleLoad (module.js:495:12)
    at Function.Module._load (module.js:487:3)
    at Module.require (module.js:577:17)
    at Module.require (pkg/prelude/bootstrap.js:1153:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/snapshot/exoframe-server/index.js:1:79)
pkg/prelude/bootstrap.js:1172
      throw error;
      ^

TypeError: server.connection is not a function
    at Object.<anonymous> (/snapshot/exoframe-server/src/index.js:18:8)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:644:10)
    at Module.load (module.js:552:32)
    at tryModuleLoad (module.js:495:12)
    at Function.Module._load (module.js:487:3)
    at Module.require (module.js:577:17)
    at Module.require (pkg/prelude/bootstrap.js:1153:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/snapshot/exoframe-server/index.js:1:79)
```

**Comment by yamalight** [comment]
Hi @M0ter! Can you please share the command you are using to start the server?

**Comment by yamalight** [comment]
Okay, have reproduced it. Something went wrong during CI and broken image got pushed to docker hub. Re-building and re-pushing correct one now..

**Comment by M0ter** [comment]
Oh, great that you could reproduce it!

**Comment by yamalight** [comment]
@M0ter ok, should be fixed now. 
Closing the issue, feel free to reopen if it still fails.
